import { expect, test } from '@playwright/test'
import { readyHistory } from './fixtures/sessionHistory'

test.describe('Analysis V1 recorded Sessions', () => {
  test.beforeEach(async ({page}) => {
    await page.addInitScript(()=>{if(!localStorage.getItem('sensi-locale'))localStorage.setItem('sensi-locale','pt')})
    await page.goto('/')
    await readyHistory(page)
  })
  test('shows an honest empty state and opens training without fake charts or trends', async ({page})=>{
    await page.getByRole('button',{name:'ANÁLISE',exact:true}).click()
    await expect(page.getByRole('heading',{name:'Análise',exact:true})).toBeVisible()
    await expect(page.getByText('Nenhuma sessão registrada')).toBeVisible()
    await expect(page.locator('.analysis-v1-chart')).toHaveCount(0)
    await page.locator('.av1-empty').getByRole('button',{name:'TREINAR',exact:true}).click()
    await expect(page.locator('.warmup-exercises')).toBeVisible()
  })
  test('filters comparable sessions, measures lower-is-better, shows context/change markers and details',async({page},info)=>{
    const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
    await page.evaluate(async()=>{
      const {makeSession}=await import('/src/testFixtures/sessions.ts')
      const {getSessionRepository}=await import('/src/sessionRepository.ts')
      const {exerciseConfig,comparisonSignature}=await import('/src/trainingSession.ts')
      const now=Date.now(),repo=getSessionRepository()
      for(let i=0;i<6;i++){
        const days=i<3?i+1:i+5, sens=i<3?.24:.27
        const session=makeSession(i<3?180:200,i+1,{exerciseId:'micro_flick',finishedAt:new Date(now-days*86400000).toISOString(),
          context:{gameId:'cs2',sensitivity:sens,dpi:800,presetId:'20000000-0000-4000-8000-000000000001',routine:{id:null,name:'Warmup',stepId:null}}})
        await repo.database.save({kind:'session',value:session},false)
      }
      const config=exerciseConfig('micro_flick','medium','medium',120,1440,900,'dot')
      await repo.database.save({kind:'session',value:makeSession(90,20,{exerciseId:'micro_flick',config,comparisonSignature:comparisonSignature('micro_flick',config),finishedAt:new Date(now-1000).toISOString()})},false)
      await repo.database.save({kind:'session',value:makeSession(1,21,{exerciseId:'micro_flick',status:'interrupted',invalidReason:'manual_abort',finishedAt:new Date(now-2000).toISOString()})},false)
      await repo.refresh()
    })
    await page.getByRole('button',{name:'ANÁLISE',exact:true}).click()
    await expect(page.getByText('Selecione um exercício para visualizar evolução.')).toBeVisible()
    await page.getByRole('combobox',{name:'Período',exact:true}).selectOption('7d')
    await page.getByRole('combobox',{name:'Exercício',exact:true}).selectOption('micro_flick')
    const configurations=page.getByRole('combobox',{name:'Configuração',exact:true})
    await expect(configurations.locator('option')).toHaveCount(2)
    const value=await configurations.locator('option').filter({hasText:/^60s/}).getAttribute('value')
    await configurations.selectOption(value!)
    await expect(page.locator('.av1-point')).toHaveCount(3)
    await expect(page.locator('.av1-period .positive')).toHaveText('+10%')
    await expect(page.getByRole('combobox',{name:'Métrica',exact:true})).toHaveValue('meanAcquisitionTimeMs')
    await page.screenshot({path:info.outputPath('analysis-trend.png'),fullPage:true})
    await page.getByRole('combobox',{name:'Período',exact:true}).selectOption('30d')
    await expect(page.locator('.av1-point')).toHaveCount(6)
    await expect(page.locator('.av1-marker')).toHaveCount(1)
    await page.locator('.av1-point').last().focus()
    const tooltip=page.locator('.analysis-chart-tooltip')
    await expect(tooltip).toContainText('180 ms')
    await expect(tooltip).toContainText('0,24')
    await expect(tooltip).toContainText('800')
    await expect(tooltip).toContainText('cm/360')
    await expect(tooltip).toContainText('Preset removido')
    await expect(tooltip).toContainText('Warmup')
    await page.screenshot({path:info.outputPath('analysis-tooltip.png'),fullPage:true})
    await page.keyboard.press('Enter')
    const dialog=page.getByRole('dialog',{name:'Detalhes da sessão'})
    await expect(dialog).toContainText('Concluída')
    await expect(dialog).toContainText('Tempo médio de aquisição')
    await page.keyboard.press('Escape')
    await expect(dialog).toHaveCount(0)
    await page.getByRole('combobox',{name:'Métrica',exact:true}).selectOption('accuracy')
    await expect(page.locator('.av1-point')).toHaveCount(6)
    await expect(page.locator('.analysis-v1-chart svg')).toHaveAttribute('aria-label','Evolução: Precisão')
    await page.getByRole('combobox',{name:'Período',exact:true}).selectOption('all')
    await expect(page.getByText('Todo período não tem comparação temporal equivalente.')).toBeVisible()
    await expect(page.locator('vite-error-overlay')).toHaveCount(0)
    expect(errors).toEqual([])
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
    await page.screenshot({path:info.outputPath('analysis-v1.png'),fullPage:true})
    await page.locator('.analysis-v1-recents').scrollIntoViewIfNeeded()
    await page.screenshot({path:info.outputPath('analysis-recent.png'),fullPage:true})
  })
  test('updates new guest sessions without reload and recalculates after confirmed deletion',async({page})=>{
    await page.getByRole('button',{name:'ANÁLISE',exact:true}).click()
    await expect(page.getByText('Nenhuma sessão registrada')).toBeVisible()
    await page.evaluate(async()=>{
      const {makeSession}=await import('/src/testFixtures/sessions.ts')
      const {getSessionRepository}=await import('/src/sessionRepository.ts')
      const repo=getSessionRepository()
      await repo.append({kind:'session',value:makeSession(321,50,{finishedAt:new Date().toISOString()})})
    })
    await expect(page.locator('.analysis-v1-recents')).toContainText('321')
    await page.getByRole('combobox',{name:'Exercício',exact:true}).selectOption('flick')
    await expect(page.locator('.av1-point')).toHaveCount(1)
    await expect(page.locator('.av1-period')).toContainText('Dados insuficientes')
    await page.locator('.analysis-v1-recents > button').click()
    page.once('dialog',d=>d.accept())
    await page.getByRole('button',{name:'Excluir sessão',exact:true}).click()
    await expect(page.getByText('Nenhuma sessão registrada')).toBeVisible()
    await expect(page.locator('.analysis-pb-list > section')).toHaveCount(0)
  })
  test('renders English filters and empty state',async({page})=>{
    await page.evaluate(()=>localStorage.setItem('sensi-locale','en'))
    await page.reload()
    await page.getByRole('button',{name:'ANALYSIS',exact:true}).click()
    await expect(page.getByText('Track your performance based on recorded training sessions.')).toBeVisible()
    await expect(page.getByRole('combobox',{name:'Period',exact:true})).toBeVisible()
    await expect(page.getByText('No sessions recorded')).toBeVisible()
  })
})
