import { expect, test } from '@playwright/test'
import { readyHistory, readSessions } from './fixtures/sessionHistory'
import { configureMicro, microHits, microTarget, startMicro } from './fixtures/microFlickArena'

test.describe('Micro Flick V1', () => {
  test.beforeEach(async ({ page }) => {
    await page.addInitScript(() => localStorage.setItem('sensi-locale', 'pt'))
  })
  test('filters the mode and mounts/cleans the shared CSS preview without Sessions, pointer lock or RAF', async ({ page }, info) => {
    const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
    await page.goto('/train'); await readyHistory(page)
    const card = page.getByRole('button', { name: /Micro Flick/ })
    await expect(card).toContainText('Treine microajustes rápidos e precisos em alvos próximos.')
    await page.getByRole('group', { name: 'Filtrar por habilidade' }).getByRole('button', { name: /Precisão/ }).click()
    await expect(card).toBeVisible()
    await page.getByRole('group', { name: 'Filtrar por habilidade' }).getByRole('button', { name: /Todos/ }).click()
    let requests = 0
    page.on('request', request => { if (request.url().includes('/rest/v1/')) requests++ })
    await page.evaluate(() => {
      const original = window.requestAnimationFrame
      window.requestAnimationFrame = callback => { document.documentElement.dataset.microRaf = String(Number(document.documentElement.dataset.microRaf ?? 0) + 1); return original(callback) }
    })
    await card.hover()
    const preview = card.locator('.warmup-preview-micro_flick')
    await expect(preview).toBeVisible()
    const frame = await preview.locator('.preview-crosshair').evaluate(el => getComputedStyle(el).left)
    await expect.poll(() => preview.locator('.preview-crosshair').evaluate(el => getComputedStyle(el).left)).not.toBe(frame)
    await page.screenshot({ path: info.outputPath('micro-preview.png') })
    await page.mouse.move(0, 0); await expect(preview).toHaveCount(0)
    await card.focus(); await expect(preview).toHaveCount(1)
    await page.keyboard.press('Tab'); await expect(preview).toHaveCount(0)
    expect(await page.evaluate(() => Number(document.documentElement.dataset.microRaf ?? 0))).toBe(0)
    expect(await readSessions(page)).toEqual([])
    expect(await page.evaluate(() => document.pointerLockElement)).toBeNull()
    expect(requests).toBe(0); expect(errors).toEqual([])
    await expect(page.locator('vite-error-overlay')).toHaveCount(0)
  })
  test('respects reduced motion and English copy, route and mobile setup layout', async ({ page }, info) => {
    await page.addInitScript(() => localStorage.setItem('sensi-locale', 'en'))
    await page.emulateMedia({ reducedMotion: 'reduce' })
    await page.goto('/train')
    const card = page.getByRole('button', { name: /Micro Flick/ })
    await expect(card).toContainText('Train fast, precise micro-adjustments on nearby targets.')
    await card.focus()
    await expect(card.locator('.preview-crosshair')).toHaveCSS('animation-name', 'none')
    await card.click()
    await expect(page).toHaveURL(/\/train\/micro-flick$/)
    await page.getByRole('button', { name: /Continue/ }).click()
    await expect(page.getByRole('button', { name: /Adaptive/ })).toHaveCount(0)
    await page.getByRole('button', { name: /Continue/ }).click()
    await expect(page.getByRole('button', { name: 'Start warm-up' })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: info.outputPath('micro-setup-en.png') })
  })
  test('completes real acquisitions, awards PB after persistence, retries and retains invalid pointer-lock loss', async ({ page }, info) => {
    test.skip(info.project.name !== 'desktop', 'Mouse pointer-lock requires desktop.')
    test.setTimeout(90000)
    const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
    await configureMicro(page); await readyHistory(page); await page.clock.install(); await startMicro(page)
    const target = await microTarget(page)
    expect(target.pixels).toBeGreaterThan(100)
    await microHits(page, 10, 300)
    await page.screenshot({ path: info.outputPath('micro-arena.png') })
    await page.clock.fastForward(61000)
    await expect(page.locator('.warmup-result-modal')).toBeVisible()
    await expect(page.locator('.personal-best-feedback')).toContainText('PRIMEIRO RECORDE REGISTRADO')
    await expect(page.getByText('Tempo médio de aquisição', { exact: true }).first()).toBeVisible()
    const first = (await readSessions(page))[0]
    if (first.exerciseId !== 'micro_flick' || first.status !== 'completed') throw new Error('Completed Micro session required')
    expect(first).toMatchObject({ exerciseId: 'micro_flick', status: 'completed', exerciseVersion: 1,
      context: { sensitivity: 1, dpi: 800 }, config: { durationSeconds: 60, input: 'mouse-pointer-lock', micro: { timeoutMs: 2000 } },
      metrics: { hits: 10, misses: 0, accuracy: 100 } })
    expect(first.config!.micro!.seed).toBeGreaterThan(0)
    expect(first.metrics!.meanAcquisitionTimeMs).toBeGreaterThan(0)
    await page.screenshot({ path: info.outputPath('micro-result.png') })
    await page.getByRole('button', { name: 'Repetir', exact: true }).click()
    await expect.poll(() => page.evaluate(() => document.pointerLockElement?.tagName)).toBe('CANVAS')
    await page.clock.runFor(3100)
    await page.evaluate(() => document.dispatchEvent(new MouseEvent('mousedown', { button: 0 })))
    await page.clock.runFor(150)
    await microHits(page, 10, 150)
    await page.clock.fastForward(61000)
    await expect(page.locator('.personal-best-feedback')).toContainText('NOVO RECORDE PESSOAL')
    const second = (await readSessions(page))[0]
    if (second.exerciseId !== 'micro_flick' || second.status !== 'completed') throw new Error('Completed Micro retry required')
    expect(second.metrics).toMatchObject({ hits: 10, misses: 1, shots: 11 })
    expect(second.metrics!.meanAcquisitionTimeMs).toBeLessThan(first.metrics!.meanAcquisitionTimeMs)
    await page.getByRole('button', { name: 'Repetir', exact: true }).click(); await page.clock.runFor(3100)
    await expect(page.locator('.warmup-countdown')).toHaveCount(0)
    await page.clock.runFor(200)
    await microTarget(page)
    await page.evaluate(async () => { document.exitPointerLock(); if (document.fullscreenElement) await document.exitFullscreen() })
    await page.getByRole('button', { name: 'INÍCIO', exact: true }).click()
    await expect.poll(async () => (await readSessions(page)).length).toBe(3)
    expect((await readSessions(page))[0]).toMatchObject({ status: 'interrupted', invalidReason: 'pointer_lock_lost' })
    await expect(page.locator('.personal-best-feedback')).toHaveCount(0)
    await page.clock.resume(); await page.reload(); await readyHistory(page)
    await page.getByRole('button', { name: 'ANÁLISE', exact: true }).click()
    await expect(page.locator('.analysis-pb-panel [data-session-id="' + second.id + '"]')).toContainText('Micro Flick')
    expect(errors).toEqual([])
  })
  test('adds, reorders, saves and executes Micro Flick in a routine with a linked session', async ({ page }, info) => {
    test.skip(info.project.name !== 'desktop', 'Routine pointer-lock execution requires desktop.')
    test.setTimeout(90000)
    page.setDefaultTimeout(10000)
    await page.goto('/')
    await page.getByRole('button', { name: /TREINAR/ }).click()
    await page.getByRole('menuitem', { name: /Rotinas/ }).click()
    await page.getByRole('button', { name: 'Criar rotina', exact: true }).click()
    await page.getByLabel('Nome da rotina').fill('Micro precision')
    await page.locator('.routine-builder-footer').getByRole('button', { name: /Adicionar exercício/ }).click()
    const dialog = page.getByRole('dialog', { name: 'Adicionar exercício' })
    await dialog.getByRole('button', { name: /Micro Flick/ }).click()
    await dialog.getByRole('button', { name: '2 min', exact: true }).click()
    await expect(dialog.getByRole('button', { name: /Adaptativa/ })).toHaveCount(0)
    await dialog.getByRole('button', { name: /Adicionar exercício/ }).click()
    const micro = page.locator('.routine-builder-item').filter({ hasText: 'Micro Flick' })
    await micro.getByRole('button', { name: 'Mover para cima' }).click()
    await expect(page.locator('.routine-builder-item').nth(2)).toContainText('Micro Flick')
    const edit = micro.getByRole('button', { name: /Editar/ })
    if (await edit.getAttribute('aria-expanded') !== 'true') await edit.click()
    await micro.getByRole('button').filter({ hasText: /^1m$/ }).click()
    await micro.getByRole('button', { name: '2m', exact: true }).click()
    for (let i = 0; i < 3; i++) await page.locator('.routine-builder-item').filter({ hasNotText: 'Micro Flick' }).first().getByRole('button', { name: 'Remover exercício' }).click()
    await page.getByRole('button', { name: 'Continuar', exact: true }).click()
    await page.getByRole('textbox', { name: 'Sensibilidade', exact: true }).fill('1')
    await page.getByRole('button', { name: /^Salvar$/ }).click()
    await expect(page.getByRole('button', { name: 'Salvo', exact: true })).toBeVisible()
    await page.getByRole('button', { name: /Voltar para biblioteca/ }).click()
    await page.reload(); await readyHistory(page)
    const card = page.locator('.routine-library-card').filter({ hasText: 'Micro precision' })
    await expect(card).toContainText('Micro Flick')
    await page.clock.install()
    await card.getByRole('button', { name: /^Iniciar$/ }).click()
    await expect.poll(() => page.evaluate(() => document.pointerLockElement?.tagName)).toBe('CANVAS')
    await page.clock.runFor(3500)
    await microHits(page, 10, 200)
    await page.clock.fastForward(121000)
    await expect(page.getByText('Rotina concluída', { exact: true })).toBeVisible()
    await expect.poll(async () => (await readSessions(page)).length).toBe(1)
    const session = (await readSessions(page))[0]
    expect(session).toMatchObject({ exerciseId: 'micro_flick', status: 'completed', config: { durationSeconds: 120 }, metrics: { hits: 10, accuracy: 100 } })
    expect(session.routineRunId).toBeTruthy()
    const run = await page.evaluate(async () => (await import('/src/sessionRepository.ts')).getSessionRepository().database.runs(null))
    expect(run).toEqual(expect.arrayContaining([expect.objectContaining({ id: session.routineRunId, status: 'completed' })]))
  })
})
