import { expect, test, type Page } from '@playwright/test'
import { mockCloud, seedGuest, login, userA, localId, remotePreset } from './fixtures/accountCloud'

test('failed import preserves guest data and interrupted confirmation retries with stable UUIDs', async ({ page, context }) => {
  const cloud = await mockCloud(context)
  await page.goto('/profile'); await seedGuest(page)
  await login(page)
  const dialog = page.getByRole('dialog', { name: 'Presets encontrados neste dispositivo' })
  cloud.failWrites = true
  await dialog.getByRole('button', { name: 'IMPORTAR PRESETS', exact: true }).click()
  await expect(dialog.getByRole('alert')).toHaveText('Não foi possível importar os presets deste dispositivo.')
  expect(cloud.rows).toHaveLength(0)
  expect(await page.evaluate(id => localStorage.getItem(`xensi-presets:imported:${id}:v1`), userA)).toBeNull()
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('xensi-player-profile')!).presets[0].id)).toBe(localId)
  cloud.failWrites = false
  cloud.delayImport = true
  await dialog.getByRole('button', { name: 'IMPORTAR PRESETS', exact: true }).click()
  await expect.poll(() => cloud.importCalls).toBe(1)
  await page.reload()
  await expect(dialog).toBeVisible()
  await dialog.getByRole('button', { name: 'IMPORTAR PRESETS', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  expect(cloud.rows.filter(row => row.id === localId)).toHaveLength(1)
  await page.goto('/profile')
  await expect(page.locator('.profile-preset-card')).toHaveCount(1)
  await expect(dialog).not.toBeVisible()
})
async function signOut(page: Page) {
  await page.locator('.xensi-user-trigger').click()
  await page.getByRole('button', { name: 'Sair', exact: true }).click()
}
async function addPreset(page: Page, name = 'New preset') {
  await page.getByRole('button', { name: 'Adicionar', exact: true }).last().click()
  const dialog = page.getByRole('dialog', { name: 'Adicionar sensibilidade', exact: true })
  await dialog.getByRole('textbox', { name: 'Nome do preset (opcional)' }).fill(name)
  await dialog.getByRole('button', { name: 'Salvar', exact: true }).click()
}

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('sensi-locale', 'pt'))
})

test('guest CRUD survives reload and primary is unique', async ({ page, context }) => {
  await mockCloud(context)
  await page.goto('/profile')
  await expect(page.getByText('Nenhuma sensibilidade salva.', { exact: true })).toBeVisible()
  await addPreset(page, 'First preset')
  await expect(page.locator('.profile-preset-card')).toHaveCount(1)
  const id = await page.evaluate(() => JSON.parse(localStorage.getItem('xensi-player-profile')!).presets[0].id)
  await page.reload()
  await expect(page.locator('.profile-preset-card')).toHaveCount(1)
  await page.getByRole('button', { name: 'Editar', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Editar sensibilidade', exact: true })
  await dialog.getByRole('textbox', { name: 'Sensibilidade', exact: true }).fill('0.8')
  await dialog.getByRole('button', { name: 'Salvar', exact: true }).click()
  await expect(page.locator('.profile-preset-card')).toContainText('0.8')
  await addPreset(page, 'Second preset')
  await page.locator('.profile-preset-card').nth(1).getByRole('button', { name: 'Definir como principal' }).click()
  await expect(page.locator('.profile-preset-card.primary')).toHaveCount(1)
  await expect(page.locator('.profile-preset-card.primary')).toContainText('Second preset')
  await page.locator('.profile-preset-card').first().getByRole('button', { name: 'Remover', exact: true }).click()
  await page.getByRole('alertdialog').getByRole('button', { name: 'Remover', exact: true }).click()
  await expect(page.locator('.profile-preset-card')).toHaveCount(1)
  expect(await page.evaluate(id => JSON.parse(localStorage.getItem('xensi-player-profile')!).presets.some((preset: { id: string }) => preset.id === id), id)).toBe(false)
})

test('guest login offers import, dismissal preserves data and import keeps cloud primary after reload', async ({ page, context }, info) => {
  const cloud = await mockCloud(context, [remotePreset()])
  await page.goto('/profile'); await seedGuest(page)
  await login(page)
  const dialog = page.getByRole('dialog', { name: 'Presets encontrados neste dispositivo' })
  await expect(dialog).toBeVisible()
  const bounds = await dialog.boundingBox()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.width).toBeLessThanOrEqual(page.viewportSize()!.width)
  expect(bounds!.height).toBeLessThanOrEqual(page.viewportSize()!.height)
  await page.screenshot({ path: info.outputPath('preset-import.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await dialog.getByRole('button', { name: 'AGORA NÃO' }).click()
  await page.goto('/profile')
  await expect(page.locator('.profile-preset-card')).toHaveCount(1)
  await expect(page.locator('.profile-preset-card')).toContainText('Cloud preset')
  expect(cloud.importCalls).toBe(0)
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('xensi-player-profile')!).presets[0].id)).toBe(localId)
  await page.getByRole('button', { name: 'IMPORTAR PRESETS', exact: true }).click()
  cloud.delayImport = true
  await dialog.getByRole('button', { name: 'IMPORTAR PRESETS', exact: true }).click()
  await expect(dialog.getByRole('button', { name: 'Importando...' })).toBeDisabled()
  await expect(dialog).not.toBeVisible()
  await expect(page.locator('.profile-preset-card')).toHaveCount(2)
  await expect(page.locator('.profile-preset-card.primary')).toContainText('Cloud preset')
  expect(cloud.rows.filter(row => row.id === localId)).toHaveLength(1)
  await page.reload()
  await expect(page.locator('.profile-preset-card')).toHaveCount(2)
  await expect(dialog).not.toBeVisible()
  expect(cloud.importCalls).toBe(1)
})

test('new account adopts guest primary and logout/account B never exposes account A data', async ({ page, context }) => {
  const cloud = await mockCloud(context)
  await page.goto('/profile'); await seedGuest(page)
  await login(page)
  await page.getByRole('dialog', { name: 'Presets encontrados neste dispositivo' }).getByRole('button', { name: 'IMPORTAR PRESETS' }).click()
  await expect(page.getByText('Presets adicionados à sua conta.', { exact: true })).toBeVisible()
  await page.goto('/profile')
  await expect(page.locator('.profile-preset-card.primary')).toContainText('Guest preset')
  await addPreset(page, 'Account A only')
  await expect(page.locator('.profile-preset-card')).toHaveCount(2)
  await signOut(page)
  await page.goto('/profile')
  await expect(page.locator('.profile-preset-card')).toHaveCount(1)
  await expect(page.locator('.profile-preset-card')).not.toContainText('Account A only')
  await login(page, 'b@example.invalid')
  await page.getByRole('dialog').getByRole('button', { name: 'AGORA NÃO' }).click()
  await page.goto('/profile')
  await expect(page.locator('.profile-preset-card')).toHaveCount(0)
  expect(cloud.rows.every(row => row.user_id === userA)).toBe(true)
})

test('cloud CRUD persists across reload and a second browser; failed writes keep prior state and allow retry', async ({ page, context, browser }, info) => {
  const cloud = await mockCloud(context, [remotePreset()])
  await login(page)
  await page.goto('/profile')
  await expect(page.locator('.profile-preset-card')).toHaveCount(1)
  cloud.failWrites = true
  await page.getByRole('button', { name: 'Editar', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Editar sensibilidade', exact: true })
  await dialog.getByRole('textbox', { name: 'Sensibilidade', exact: true }).fill('0.5')
  await dialog.getByRole('button', { name: 'Salvar', exact: true }).click()
  await expect(dialog.getByText('Não foi possível sincronizar seus presets. Tente novamente.')).toBeVisible()
  expect(cloud.rows[0].sensitivity).toBe(.4)
  cloud.failWrites = false
  await dialog.getByRole('button', { name: 'Salvar', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await addPreset(page, 'Second cloud')
  await expect(page.locator('.profile-preset-card')).toHaveCount(2)
  await page.locator('.profile-preset-card').last().getByRole('button', { name: 'Definir como principal' }).click()
  await expect(page.locator('.profile-preset-card.primary')).toContainText('Second cloud')
  await page.reload()
  await expect(page.locator('.profile-preset-card')).toHaveCount(2)
  const secondContext = await browser.newContext({ viewport: { width: 1440, height: 900 }, baseURL: 'http://127.0.0.1:5175/' })
  try {
    await mockCloud(secondContext, cloud.rows)
    const second = await secondContext.newPage()
    await second.addInitScript(() => localStorage.setItem('sensi-locale', 'pt'))
    await login(second)
    await second.goto('/profile')
    await expect(second.locator('.profile-preset-card')).toHaveCount(2)
    await expect(second.locator('.profile-preset-card.primary')).toContainText('Second cloud')
    await second.screenshot({ path: info.outputPath('presets-second-browser.png'), fullPage: true })
  } finally { await secondContext.close() }
  await page.locator('.profile-preset-card').first().getByRole('button', { name: 'Remover', exact: true }).click()
  await page.getByRole('alertdialog').getByRole('button', { name: 'Remover', exact: true }).click()
  await expect(page.locator('.profile-preset-card')).toHaveCount(1)
  await page.getByRole('button', { name: 'Atualizar presets' }).click()
  await expect(page.locator('.profile-preset-card')).toHaveCount(1)
})
