import { expect, test, type Page } from '@playwright/test'

async function openTraining(page: Page) {
  await page.getByRole('button', { name: 'TREINAR', exact: true }).click()
  await page.getByRole('menuitem', { name: /Minigames/ }).click()
  await page.getByRole('button', { name: /Target Switch/ }).click()
}
async function seed(page: Page) {
  await page.evaluate(() => {
    const base = { gameId: 'cs2', sensitivity: .65, dpi: 800, createdAt: '2026-09-05', updatedAt: '2026-09-05' }
    localStorage.setItem('xensi-player-profile', JSON.stringify({ presets: [
      { ...base, id: '10000000-0000-4000-8000-000000000001', name: 'Principal', isPrimary: true },
      { ...base, id: '10000000-0000-4000-8000-000000000002', name: 'Teste', sensitivity: .7, isPrimary: false },
    ] }))
    window.dispatchEvent(new Event('xensi-profile-updated'))
  })
}

test.describe('shared presets and game identity', () => {
  test.beforeEach(async ({ page }) => {
    await page.addInitScript(() => localStorage.setItem('sensi-locale', 'pt'))
    await page.goto('./')
  })

  test('creates a profile preset and reuses it across training, calibration and conversion', async ({ page, isMobile }, info) => {
    test.setTimeout(90000)
    await page.goto('./profile')
    await expect(page.getByRole('heading', { name: 'Perfil', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Adicionar sensibilidade' }).click()
    await page.getByRole('dialog', { name: 'Adicionar sensibilidade' }).getByRole('button', { name: 'Counter-Strike 2' }).click()
    await page.getByRole('option', { name: 'Counter-Strike 2' }).click()
    await page.getByRole('textbox', { name: 'Sensibilidade', exact: true }).fill('0.65')
    await page.getByRole('textbox', { name: 'DPI', exact: true }).fill('800')
    await page.getByRole('button', { name: 'Salvar', exact: true }).click()
    await expect(page.locator('.profile-preset-card .xensi-game-badge')).toHaveText('CS')
    await openTraining(page)
    const dialog = page.getByRole('dialog')
    const primaryGame = dialog.getByRole('button', { name: /Counter-Strike 2/ })
    await expect(primaryGame).toHaveAttribute('aria-pressed', 'true')
    await expect(primaryGame).toContainText('Principal')
    await dialog.getByRole('button', { name: /Continuar/ }).click()
    await expect(dialog.getByText('Preset principal carregado', { exact: true })).toBeVisible()
    await expect(dialog.getByRole('textbox', { name: 'Sensibilidade', exact: true })).toHaveValue('0.65')
    await expect(dialog.getByRole('textbox', { name: 'DPI do mouse' })).toHaveValue('800')
    await expect(dialog.getByText('79.93 cm/360')).toBeVisible()
    await dialog.getByRole('textbox', { name: 'Sensibilidade', exact: true }).fill('0.70')
    await expect(dialog.getByText('Modificado para esta sessão', { exact: true })).toBeVisible()
    await dialog.getByRole('button', { name: /Voltar/ }).click()
    await dialog.getByRole('button', { name: /Continuar/ }).click()
    await expect(dialog.getByRole('textbox', { name: 'Sensibilidade', exact: true })).toHaveValue('0.70')
    await dialog.getByRole('button', { name: /Continuar/ }).click()
    if (!isMobile) {
      await page.clock.install()
      await dialog.getByRole('button', { name: /Iniciar aquecimento/ }).click()
      await expect.poll(() => page.evaluate(() => document.pointerLockElement?.tagName)).toBe('CANVAS')
      await page.clock.runFor(65000)
      await expect(page.locator('.warmup-result-modal')).toBeVisible()
      const snapshot = await page.evaluate(async () => (await (await import('/src/sessionRepository.ts')).getSessionRepository().database.sessions(null))[0].context)
      expect(snapshot).toMatchObject({ gameId: 'cs2', sensitivity: .7, dpi: 800 })
      expect(snapshot.presetId).toBeTruthy()
      await page.locator('.warmup-result-modal').getByRole('button', { name: /Sair/ }).click()
      await page.clock.resume()
    } else await dialog.getByRole('button', { name: 'Fechar', exact: true }).click()
    expect(await page.evaluate(() => JSON.parse(localStorage.getItem('xensi-player-profile')!).presets[0].sensitivity)).toBe(.65)
    await page.getByRole('button', { name: 'CALIBRAR', exact: true }).click()
    await page.getByRole('menuitem', { name: /Calibrar sensibilidade/ }).click()
    await page.getByRole('button', { name: 'Configurar calibrador', exact: true }).click()
    const finder = page.getByRole('dialog')
    await expect(finder.locator('.xensi-wizard-stepper > div')).toHaveCount(2)
    await expect(finder.getByRole('button', { name: /Counter-Strike 2/ })).toHaveAttribute('aria-pressed', 'true')
    await finder.getByRole('button', { name: /Continuar/ }).click()
    await expect(finder.getByRole('textbox', { name: 'Sensibilidade', exact: true })).toHaveValue('0.65')
    await expect(finder.getByRole('textbox', { name: 'DPI do mouse' })).toHaveValue('800')
    await expect(finder.getByText('79.93 cm/360')).toBeVisible()
    await finder.getByRole('textbox', { name: 'Sensibilidade', exact: true }).fill('0.69')
    await finder.getByRole('button', { name: /Voltar/ }).click()
    await finder.getByRole('button', { name: /Continuar/ }).click()
    await expect(finder.getByRole('textbox', { name: 'Sensibilidade', exact: true })).toHaveValue('0.69')
    await expect(finder.getByText('Modificado para esta sessão', { exact: true })).toBeVisible()
    const finderBounds = await finder.boundingBox()
    expect(finderBounds!.width).toBeLessThanOrEqual(page.viewportSize()!.width)
    expect(finderBounds!.height).toBeLessThanOrEqual(page.viewportSize()!.height)
    await page.screenshot({ path: `test-results/finder-settings-${info.project.name}.png`, animations: 'disabled' })
    await finder.getByRole('button', { name: 'Iniciar calibração', exact: true }).click()
    await expect(page.getByText('Pronto para a calibração', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Sair', exact: true }).click()
    await page.getByRole('button', { name: 'CONVERTER', exact: true }).click()
    await expect(page.getByLabel('Sensibilidade atual', { exact: true })).toHaveValue('0.65')
    await expect(page.getByLabel('DPI de origem')).toHaveValue('800')
    await page.getByLabel('Sensibilidade atual', { exact: true }).fill('0.72')
    await page.getByLabel('Jogo de destino', { exact: true }).selectOption('valorant')
    await expect(page.getByLabel('Sensibilidade atual', { exact: true })).toHaveValue('0.72')
  })

  test('renders a compact selector, explicit presets and stable manual edits', async ({ page }, info) => {
    await seed(page)
    await openTraining(page)
    const dialog = page.getByRole('dialog')
    const cs = dialog.getByRole('button', { name: /Counter-Strike 2/ })
    await expect(cs).toContainText('0.65 · 800 DPI')
    await expect(dialog.getByRole('heading', { name: 'SEUS JOGOS' })).toBeVisible()
    await expect(dialog.getByRole('heading', { name: 'OUTROS JOGOS' })).toBeVisible()
    await expect(cs).toHaveAttribute('aria-pressed', 'true')
    await expect(dialog.locator('img')).toHaveCount(0)
    await page.keyboard.press('Tab')
    await cs.focus()
    await expect(cs).toBeFocused()
    await expect(cs).toHaveCSS('outline-style', 'solid')
    await page.screenshot({ path: `test-results/game-picker-${info.project.name}.png`, animations: 'disabled' })
    await dialog.getByRole('button', { name: /Call of Duty: Black Ops 7/ }).click()
    await expect(dialog.getByRole('button', { name: /Continuar/ })).toBeEnabled()
    await cs.click()
    await dialog.getByRole('button', { name: /Continuar/ }).click()
    await dialog.getByLabel('Preset utilizado').selectOption('10000000-0000-4000-8000-000000000002')
    await expect(dialog.getByRole('textbox', { name: 'Sensibilidade', exact: true })).toHaveValue('0.7')
    await dialog.getByRole('textbox', { name: 'Sensibilidade', exact: true }).fill('0.73')
    await page.evaluate(() => window.dispatchEvent(new Event('xensi-profile-updated')))
    await dialog.getByRole('button', { name: /Normal/ }).click()
    await expect(dialog.getByRole('textbox', { name: /Sensibilidade/ })).toHaveValue('0.73')
    expect(await page.evaluate(() => JSON.parse(localStorage.getItem('xensi-player-profile')!).presets[0].sensitivity)).toBe(.65)
    const bounds = await dialog.boundingBox()
    expect(bounds!.x).toBeGreaterThanOrEqual(0)
    expect(bounds!.width).toBeLessThanOrEqual(page.viewportSize()!.width)
    expect(bounds!.height).toBeLessThanOrEqual(page.viewportSize()!.height)
    await page.keyboard.press('Escape')
    await expect(dialog).toHaveCount(0)
    await expect(page.getByRole('button', { name: /Target Switch/ })).toBeVisible()
  })

  test('keeps anonymous training available and respects reduced motion', async ({ page }) => {
    await page.emulateMedia({ reducedMotion: 'reduce' })
    await openTraining(page)
    const dialog = page.getByRole('dialog')
    await expect(dialog.getByRole('heading', { name: 'OUTROS JOGOS' })).toBeVisible()
    const game = dialog.getByRole('button', { name: /Valorant/ })
    await game.focus()
    await page.keyboard.press('Space')
    await expect(game).toHaveAttribute('aria-pressed', 'true')
    await expect(game).toHaveCSS('transition-duration', '0s')
    await dialog.getByRole('button', { name: /Continuar/ }).click()
    await dialog.getByRole('textbox', { name: 'Sensibilidade', exact: true }).fill('0.25')
    await dialog.getByRole('textbox', { name: 'DPI do mouse' }).fill('1600')
    await expect(dialog.getByRole('button', { name: /Continuar/ })).toBeEnabled()
    expect(await page.evaluate(() => localStorage.getItem('xensi-player-profile'))).toBeNull()
  })
})
