const pt = {
  deleteSession: 'Excluir sessão', confirmDelete: 'Excluir esta sessão? Os dados derivados e o PB serão recalculados.', deleteError: 'Não foi possível excluir a sessão.',
  title: 'Análise', subtitle: 'Acompanhe seu desempenho com base nas sessões registradas.',
  period: 'Período', exercise: 'Exercício', metric: 'Métrica', configuration: 'Configuração',
  '7d': '7 dias', '30d': '30 dias', '90d': '90 dias', all: 'Todo período', allExercises: 'Todos',
  mean: 'Média recente', median: 'Mediana recente', variation: 'Variação (CV)', count: 'Sessões',
  chart: 'Evolução', select: 'Selecione um exercício para visualizar evolução.', insufficient: 'Dados insuficientes para calcular tendência.',
  current: 'Atual', previous: 'Anterior', comparison: 'Comparação de períodos', noComparison: 'Todo período não tem comparação temporal equivalente.',
  recent: 'Sessões recentes', empty: 'Nenhuma sessão registrada', emptyText: 'Complete alguns treinos para começar a visualizar sua evolução.',
  train: 'TREINAR', loading: 'Carregando análise...', error: 'Não foi possível carregar a análise.', refresh: 'Atualizar análise',
  changed: 'Mudança de sensibilidade/preset', preset: 'Preset', deletedPreset: 'Preset removido', noPreset: 'Sem preset salvo',
  details: 'Detalhes da sessão', duration: 'Duração', game: 'Jogo', sensitivity: 'Sensibilidade', routine: 'Rotina',
  limited: 'O gráfico mostra as últimas 300 sessões; as estatísticas incluem todo o período.',
  noMetric: 'Nenhum valor válido para esta métrica.', noPB: 'Sem PB nesta configuração', primaryPB: 'PB da métrica principal', overview: 'Exercícios no período',
}
export const ANALYSIS_COPY = {
  pt,
  en: {
    deleteSession: 'Delete session', confirmDelete: 'Delete this session? Derived data and PB will be recalculated.', deleteError: 'Could not delete the session.',
    title: 'Analysis', subtitle: 'Track your performance based on recorded training sessions.',
    period: 'Period', exercise: 'Exercise', metric: 'Metric', configuration: 'Configuration',
    '7d': '7 days', '30d': '30 days', '90d': '90 days', all: 'All time', allExercises: 'All',
    mean: 'Recent average', median: 'Recent median', variation: 'Variation (CV)', count: 'Sessions',
    chart: 'Performance over time', select: 'Select an exercise to view progress.', insufficient: 'Not enough data to calculate a trend.',
    current: 'Current', previous: 'Previous', comparison: 'Period comparison', noComparison: 'All time has no equivalent previous period.',
    recent: 'Recent sessions', empty: 'No sessions recorded', emptyText: 'Complete a few training sessions to start seeing your progress.',
    train: 'TRAIN', loading: 'Loading analysis...', error: 'Could not load analysis.', refresh: 'Refresh analysis',
    changed: 'Sensitivity/preset changed', preset: 'Preset', deletedPreset: 'Deleted preset', noPreset: 'No saved preset',
    details: 'Session details', duration: 'Duration', game: 'Game', sensitivity: 'Sensitivity', routine: 'Routine',
    limited: 'The chart shows the latest 300 sessions; statistics include the full period.',
    noMetric: 'No valid values for this metric.', noPB: 'No PB for this configuration', primaryPB: 'Primary metric PB', overview: 'Exercises in period',
  },
  es: {
    deleteSession: 'Eliminar sesión', confirmDelete: '¿Eliminar esta sesión? Los datos derivados y el PB se recalcularán.', deleteError: 'No se pudo eliminar la sesión.',
    title: 'Análisis', subtitle: 'Sigue tu rendimiento según las sesiones de entrenamiento registradas.',
    period: 'Período', exercise: 'Ejercicio', metric: 'Métrica', configuration: 'Configuración',
    '7d': '7 días', '30d': '30 días', '90d': '90 días', all: 'Todo el período', allExercises: 'Todos',
    mean: 'Promedio reciente', median: 'Mediana reciente', variation: 'Variación (CV)', count: 'Sesiones',
    chart: 'Evolución', select: 'Selecciona un ejercicio para ver tu evolución.', insufficient: 'Datos insuficientes para calcular una tendencia.',
    current: 'Actual', previous: 'Anterior', comparison: 'Comparación de períodos', noComparison: 'Todo el período no tiene un período anterior equivalente.',
    recent: 'Sesiones recientes', empty: 'No hay sesiones registradas', emptyText: 'Completa algunos entrenamientos para empezar a ver tu evolución.',
    train: 'ENTRENAR', loading: 'Cargando análisis...', error: 'No se pudo cargar el análisis.', refresh: 'Actualizar análisis',
    changed: 'Cambio de sensibilidad/preset', preset: 'Preset', deletedPreset: 'Preset eliminado', noPreset: 'Sin preset guardado',
    details: 'Detalles de la sesión', duration: 'Duración', game: 'Juego', sensitivity: 'Sensibilidad', routine: 'Rutina',
    limited: 'El gráfico muestra las últimas 300 sesiones; las estadísticas incluyen todo el período.',
    noMetric: 'No hay valores válidos para esta métrica.', noPB: 'Sin PB en esta configuración', primaryPB: 'PB de la métrica principal', overview: 'Ejercicios en el período',
  },
} satisfies Record<string, Record<keyof typeof pt, string>>
