export const PERSONAL_BEST_COPY = {
  pt: { first: 'PRIMEIRO RECORDE REGISTRADO', new: 'NOVO RECORDE PESSOAL', previous: 'Recorde anterior', newBest: 'Novo recorde',
    title: 'Recordes pessoais', empty: 'Nenhum recorde registrado', emptyText: 'Complete um treino para registrar seu primeiro Personal Best.',
    loading: 'Carregando recordes...', unavailable: 'Recorde pessoal indisponível no momento.', retry: 'Atualizar recordes',
    configuration: 'Configuração', all: 'Ver todos os recordes', less: 'Ver menos', input: 'Entrada', mouse: 'Mouse', controller: 'Controle',
    arena: 'Área', crosshair: 'Mira', targets: 'Alvos', scale: 'Escala do alvo', speed: 'Velocidade', dwell: 'Permanência', respawn: 'Intervalo', opening: 'Abertura', radius: 'Raio' },
  en: { first: 'FIRST PERSONAL BEST RECORDED', new: 'NEW PERSONAL BEST', previous: 'Previous best', newBest: 'New best',
    title: 'Personal bests', empty: 'No personal bests yet', emptyText: 'Complete a training session to record your first Personal Best.',
    loading: 'Loading personal bests...', unavailable: 'Personal best unavailable right now.', retry: 'Refresh personal bests',
    configuration: 'Configuration', all: 'Show all personal bests', less: 'Show less', input: 'Input', mouse: 'Mouse', controller: 'Controller',
    arena: 'Arena', crosshair: 'Crosshair', targets: 'Targets', scale: 'Target scale', speed: 'Speed', dwell: 'Dwell', respawn: 'Interval', opening: 'Opening', radius: 'Radius' },
  es: { first: 'PRIMER RÉCORD REGISTRADO', new: 'NUEVO RÉCORD PERSONAL', previous: 'Récord anterior', newBest: 'Nuevo récord',
    title: 'Récords personales', empty: 'No hay récords registrados', emptyText: 'Completa un entrenamiento para registrar tu primer Personal Best.',
    loading: 'Cargando récords...', unavailable: 'Récord personal no disponible en este momento.', retry: 'Actualizar récords',
    configuration: 'Configuración', all: 'Ver todos los récords', less: 'Ver menos', input: 'Entrada', mouse: 'Ratón', controller: 'Mando',
    arena: 'Área', crosshair: 'Mira', targets: 'Objetivos', scale: 'Escala del objetivo', speed: 'Velocidad', dwell: 'Permanencia', respawn: 'Intervalo', opening: 'Apertura', radius: 'Radio' },
} as const
